Update eslint-check.yml

diff --git a/.github/workflows/eslint-check.yml b/.github/workflows/eslint-check.yml
--- a/.github/workflows/eslint-check.yml
+++ b/.github/workflows/eslint-check.yml
@@ -1,7 +1,11 @@
 name: ESLint Check
 on:
-  push:
-    branches: ["*"]
+  pull_request:
+    branches: ["graphql"]
+    paths:
+      - "**/*.ts"
+      - "**/*.tsx"
+      - ".github/workflows/eslint-check.yml"
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -14,6 +18,11 @@ jobs:
       - name: Install Dependencies
         run: npm install
       - name: Run ESLint
-        run: npx eslint 'src/**/*.{ts,tsx}' --quiet || exit 1
+        run: |
+          result=$(npx eslint 'src/**/*.{ts,tsx}' --quiet; echo $?)
+          if [ $result -ne 0 ]; then
+            echo "ESLint check failed"
+            exit 1
+          fi
       - name: Check for TypeScript errors
         run: npx tsc --noEmit
